### ISSUE TITLE
bootloader - TX led not blink when uploading

### ISSUE THREAD

**Issue by bobricius** [arduino/ArduinoCore-samd#1]
please add TX, RX led flashing on upload to bootloader

**Comment by cmaglie** [comment]
Thanks for reporting.
It should be easy to fix, I'll implement it in the coming days.

**Comment by bobricius** [comment]
I am sorry for disturbing, is there any release date? or release date for 1.6.2 ? Thanks

**Comment by rory-littleBits** [comment]
I still don't see this addressed in v1.6.7. Are there any updates or an ETA available?

**Comment by sandeepmistry** [comment]
@bobricius @rory-littleBits I've submitted #122 to resolve this. It's based on #64 and #69, I've cherry-pick various commits, rebased, and made a few changes.
