### ISSUE TITLE
Zero min() and max functions don't compile

### ISSUE THREAD

**Issue by wholder** [arduino/ArduinoCore-samd#10]
Trying to compile code like this on the Zero:

    int test = min(1,2);

results in "error: 'min' was not declared in this scope
'min' was not declared in this scope".  Same problem for max().

Note: tested on 1.6.5 running on OS X.

**Comment by cmaglie** [comment]
There is indeed a problem with `min` and `max`, in #12 there is a possible solution.

**Comment by wholder** [comment]
Since this issue seems to resides in code now managed by the Boards Manager, what steps will be needed to update once the changes make their way into an hourly build?  Will just getting the correct hourly build take care of it, or will I additionally need to use the Boards Manager to update the same core code?

Wayne
