### ISSUE TITLE
String() class fails to construct properly with floats and doubles

### ISSUE THREAD

**Issue by mwmckee** [arduino/ArduinoCore-samd#109]
Hitting an issue where using Arduino's String class constructor fails to create a string when given an initial value that is a float or a double.

Simple repro: Serial.print(String(1.1)) doesn't print anything.

A repro program is attached. This program works when targeting an Uno. This is with the following two packages installed:
◾Arduino SAMD Boards (32-bits ARM Cortex-M0+), version 1.6.2
◾Arduino SAMD Core - (build 1), version 1.6.2-build-2

[string_bug_repro.txt](https://github.com/arduino/ArduinoCore-samd/files/125370/string_bug_repro.txt)

**Comment by mwmckee** [comment]
A workaround is to use the following line of code to force link `printf`'s `float` support

**Comment by sandeepmistry** [comment]
@mwmckee I've submitted PR #111 to correct this, @Arduino bot has created a build that you can try out  here: https://github.com/arduino/ArduinoCore-samd/pull/111#issuecomment-183071608.
