### ISSUE TITLE
openocd recipe has bootloader 0 (no prot?)

### ISSUE THREAD

**Issue by ladyada** [arduino/ArduinoCore-samd#124]
heya folx - i was writing a tutorial and noticed that your recipe for openocd programming the bootloader is

`tools.openocd.bootloader.pattern="{path}/{cmd}" {bootloader.verbose} -s "{path}/share/openocd/scripts/" -f "{runtime.platform.path}/variants/{build.variant}/{build.openocdscript}" -c "telnet_port disabled; init; halt; at91samd bootloader 0; program {{{runtime.platform.path}/bootloaders/{bootloader.file}}} verify reset; shutdown"`

in particular the "at91samd bootloader 0" is required to unset bootloader protection before uploading, so thats good. however, that protection is never re-set with "at91samd bootloader 8192" or something after programverify.... I'm pretty new to openocd but thought it was worth checking :)

**Comment by cmaglie** [comment]
Seems to work! Thank you ;-)

**Comment by ladyada** [comment]
:+1:
