### ISSUE TITLE
Bossac "1.6.1-arduino" fork source

### ISSUE THREAD

**Issue by ladyada** [arduino/ArduinoCore-samd#135]
hiya, i am doing some poking at bossac!

were any changes made for "version()=v2.0 [Arduino:XYZ]"? i could not locate the arduino repo on github, just compiled binaries. maybe i'm not lookin the right place?

thx! :)

**Comment by ladyada** [comment]
ok, did find a version over at ardiuno-org but i think its older v1.5? who knows ¯\_(ツ)_/¯

**Comment by facchinm** [comment]
@ladyada maybe https://github.com/shumatech/BOSSA/tree/arduino is the branch you are looking for :wink:

**Comment by ladyada** [comment]
ooh! yes good to know arduino.cc can commit to it if necessary, it looked like an 'abandoned' clone of the soruceforce page. thx! :)
