### ISSUE TITLE
Serial.write(buf, Len) always returns 0

### ISSUE THREAD

**Issue by NickWaterton** [arduino/ArduinoCore-samd#138]
This function is supposed to return the actual number of bytes written. On the USB (native) port it always returns 0.

**Comment by sandeepmistry** [comment]
Hi @NickWaterton,

I can confirm this behaviour with the following sketch:

```arduino
void setup() {
  SerialUSB.begin(9600);

  while(!SerialUSB);
}

void loop() {
  int written = SerialUSB.println("hello");
  
  SerialUSB.println(written);

  delay(1000);
}
```

It prints:

```
hello
0
```

instead of:

```
hello
7
```

I've submitted #143 to resolve this. You can try it out by following these instructions: https://github.com/arduino/ArduinoCore-samd/pull/143#issuecomment-222177134
