### ISSUE TITLE
Reset programatically

### ISSUE THREAD

**Issue by javorosas** [arduino/ArduinoCore-samd#141]
Is there a way to reset the board by software?

**Comment by facchinm** [comment]
Hi @javorosas ,
if you take a look at https://github.com/arduino/ArduinoCore-samd/blob/dd6890a3782b6edf880c4d7da5e46bf77b71478b/cores/arduino/Reset.cpp#L34 there is the method we use to reset the board for programming (it also erases the application, so you may only want to call `NVIC_SystemReset()` to simply reset)
