### ISSUE TITLE
PWM on pin #13 fix

### ISSUE THREAD

**Issue by ladyada** [arduino/ArduinoCore-samd#155]
heya - it seems pin #13 pwm analogwrite() doesnt work? a change to the variant.cpp fixes:

```
  // 13 (LED)
  { PORTA, 17, PIO_PWM, (PIN_ATTR_DIGITAL|PIN_ATTR_PWM|PIN_ATTR_TIMER), No_ADC_Channel, PWM2_CH1, TCC2_CH1, EXTERNAL_INT_1 }, // TCC2/WO[1]

```
(basically, tell it what channel to tweak) - all other PWMs are :+1:

**Comment by sandeepmistry** [comment]
@ladyada thanks for letting us know!

Closed via #156.
