### ISSUE TITLE
Lack of Watchdog API for Zero/MKR1000 boards (and why not, for AVR-based boards for homogeneity)

### ISSUE THREAD

**Issue by q2dg** [arduino/ArduinoCore-samd#160]
For Due it was done in this PR: https://github.com/arduino/Arduino/pull/3111
In fact, I already asked for this here (https://github.com/arduino/Arduino/issues/3889#issuecomment-144875275) but with no luck

**Comment by FRVisser** [comment]
There is 3th party: https://github.com/SodaqMoja/Sodaq_wdt

**Comment by q2dg** [comment]
Oh, it seems interesting, thanks!!
I'll close the issue but if someone consider it should remain open, I'll reopen it
