### ISSUE TITLE
PWM doesn't work on D7 but on D39 (both PA21)?!

### ISSUE THREAD

**Issue by Adminius** [arduino/ArduinoCore-samd#178]
D7 and D39 are the same PA21 port.
Why can i use PWM with 39 but not with 7?
https://github.com/arduino/ArduinoCore-samd/blob/master/variants/arduino_zero/variant.cpp#L127
https://github.com/arduino/ArduinoCore-samd/blob/master/variants/arduino_zero/variant.cpp#L188

I think it would be better to use this line for D7:
`{ PORTA, 21, PIO_PWM_ALT, (PIN_ATTR_DIGITAL|PIN_ATTR_PWM), No_ADC_Channel, PWM0_CH7, TCC0_CH7, EXTERNAL_INT_5 }`

**Comment by cmaglie** [comment]
Fixed with #191, thank you!
