### ISSUE TITLE
Sketch stops working when WiFi.h is included

### ISSUE THREAD

**Issue by agdl** [arduino/ArduinoCore-samd#18]
I tried to use the WiFi examples on the zero (in particular ScanNetworks). It doesn't work. I made some test and i notice that even this simple sketch

```
#include <SPI.h>
#include <WiFi.h>

void setup() {
  Serial.begin(115200);

  Serial.println("Serial started");

  while(1);
}

void loop() {
}
```

stops working when WiFi.h is included

IDE1.6.6 ubuntu 14.04

**Comment by justinplatz** [comment]
When will a fix be pushed?

**Comment by facchinm** [comment]
Pushed :smile:

**Comment by facchinm** [comment]
The library update will be available soon
