### ISSUE TITLE
Some PWMs may have more than 8bit resolution

### ISSUE THREAD

**Issue by Adminius** [arduino/ArduinoCore-samd#181]
Hello,
i'm disappointed about analogWriteResolution function...
as you can see [https://github.com/arduino/ArduinoCore-samd/blob/master/cores/arduino/wiring_analog.c#L215](https://github.com/arduino/ArduinoCore-samd/blob/master/cores/arduino/wiring_analog.c#L215)
the input value is mapped to 8 bit value, so it doesn't matter wich resolution is set by analogWriteResolution()

can you check this, pls?
Thx

**Comment by tuxedo0801** [comment]
@cmaglie & Co... 
No comments so far?

**Comment by cmaglie** [comment]
The purpose of the `analogWriteResolution(..)` is to provide a portable API so you can write a sketch like:

```
analogWriteResolution(10);
analogWrite(1, 600);
```

and it will work consistently across all platform/boards (even different CPU architectures!) and at the same time deliver the maximum accuracy available on each board.
Of course if you exceed the hardware capabilities the value passed in analogWrite will be truncated, writing `analogWriteResolution(100)` will not magically give you a PWM with 100 bits of resolution...
The SAMD21 has 8-bit PWMs, so the values are mapped to 8 bit to match hardware capabilities.

**Comment by Adminius** [comment]
All PWM TCC und TC timers (0-5) are 16bit timer and not 8bit. But analogWrite can only 8bit...
It would be nice, if at least TCC timer could be tuned to at least 12bit resolution. (TC timer can only 8 or 16 :( )

**Comment by cmaglie** [comment]
I see, I've changed the issue subject accordingly.

@Adminius can you provide a PR for that?

**Comment by Adminius** [comment]
@cmaglie with this PR it ist possible to set resolution with analogWriteResolution up to 16 bit and set analogWrite values up to 65535.
PWM frequency is still 732 Hz

**Comment by Adminius** [comment]
@cmaglie, @facchinm any news?

**Comment by cmaglie** [comment]
Merged #226, thank you!
