### ISSUE TITLE
Invalid driver signature for CircuitPlay Express

### ISSUE THREAD

**Issue by dlabun** [arduino/ArduinoCore-samd#206]
The driver packaged within the SAMD core for the Adafruit CircuitPlay Express does not have a valid signature, causing Windows validation errors when you attempt to install 1.6.10 or 1.6.11 of the core. There were a bunch of drivers on the Arduino repository that were fixed, looks like this driver needs updating as well.

**Comment by facchinm** [comment]
Thanks for spotting this! Backporting https://github.com/arduino/Arduino/commit/123c231c8e8c9b1d610d4ad26a294830c624e1bc should fix the issue @cmaglie

**Comment by cmaglie** [comment]
> Backporting arduino/Arduino@123c231 should fix the issue

no, the drivers are different, it requires to be re-sign from Adafruit

/cc @ladyada

**Comment by dlabun** [comment]
On a related side note, What board is this driver even intended for? I couldn't find anything on the Adafruit website, making me wonder if this driver is even necessary.

**Comment by ladyada** [comment]
[cplayexpress.zip](https://github.com/arduino/ArduinoCore-samd/files/724915/cplayexpress.zip)

here's latest signed driver. for Unknown Reasons i couldnt rename cdc_vista.cat without it complaining about the signature :/

cmaglie, can you verify for me that you get no warnings? thx :)

**Comment by cmaglie** [comment]
it works, thanks!
