### ISSUE TITLE
Float support in snprintf

### ISSUE THREAD

**Issue by descampsa** [arduino/ArduinoCore-samd#217]
Float support in snprintf seems to be enabled or disabled depending if String is used in the code or not.
See https://github.com/arduino/Arduino/issues/6024

Not sure if it is a bug or intended behaviour, but that can be confusing for beginners.

**Comment by sandeepmistry** [comment]
Hi @descampsa,

> Not sure if it is a bug or intended behaviour, but that can be confusing for beginners.

Yes, it's the intended behaviour as discussed in https://github.com/arduino/Arduino/issues/6024#issuecomment-284814407 - most Arduino users do not use `printf` so it would take additional space.


For advanced user, float support can be added via adding the following to your sketch.
```
asm(".global _printf_float");
```
