### ISSUE TITLE
analog and serial issue

### ISSUE THREAD

**Issue by Makeblock-official** [arduino/ArduinoCore-samd#22]
1. no analog output on 7
2. program keep go into serial error irq if serial connect to nothing, 
the function clearStatusUART seems not working

**Comment by cmaglie** [comment]
Hi @Makeblock-official 

1. pin 2 and 7 are not supposed to have PWM

2. Yesterday I've published the release 1.6.1 of the SAMD core, that contains this fix to a similar problem: 49fe43806
may it be of any help for you?

**Comment by cmaglie** [comment]
closing for lack of feedback, if the problem persists please provide more details on how to reproduce the bug.
