### ISSUE TITLE
Two fixes to Adafruit Circuit Playground Express

### ISSUE THREAD

**Issue by ladyada** [arduino/ArduinoCore-samd#240]
hiya, we have a fixed up Variant.cpp & Variant.h that matches the current shipping hardware. 
we also have a fix for "CRYSTALLESS" which will make it reliable on start (thanks @tannnewt!)

please let Phil and I know the best way to submit the two sets of changes: one is to the CPX variant files and one is to startup.c. Can do a pull request or attach a patchfile.

We'll post up on the dev list too.

**Comment by cmaglie** [comment]
Just send a PR, so we can examine it. Once merged it will be published on the next samd core release.

**Comment by ladyada** [comment]
hiya is there an ETA for the next samd core release?

**Comment by cmaglie** [comment]
Fixed by #240
