### ISSUE TITLE
memory overwrite in samd21_host.c

### ISSUE THREAD

**Issue by alanambrose** [arduino/ArduinoCore-samd#271]
I believe this fix is needed in UHD_Init.  I tracked down an overwrite in some memory I had allocated which was being stamped on by the loop below with the uint32 cast (because sizeof() returns # bytes and the uint32 casting counts up in 32-bit **words**). The replacement memset works fine.:

	// ACA - memory overwrite!!
	memset(usb_pipe_table,0,sizeof(usb_pipe_table));
	/*
	for (i = 0; i < sizeof(usb_pipe_table); i++)
	{
		(*(uint32_t *)(&usb_pipe_table[0] + i)) = 0;
	}
	*/

**Comment by sandeepmistry** [comment]
Hi @alanambrose,

The suggestion looks good to me, would you like to submit a pull request for it?

**Comment by sandeepmistry** [comment]
Closed via https://github.com/arduino/ArduinoCore-samd/pull/355.
