### ISSUE TITLE
String Descriptor fails to write iManufacturer and iProduct

### ISSUE THREAD

**Issue by adammunich** [arduino/ArduinoCore-samd#274]
It appears that iManufacturer and iProduct are not filled in for HID descriptor requests. This seems odd, as bool USBDeviceClass::sendStringDescriptor(const uint8_t *string, uint8_t maxlen){} seems to have the strings "Arduino LLC" and "Arduino Zero" passed to it successfully. 

----
Connection Information:
------------------------------
Device current bus speed: FullSpeed
Device supports USB 1.1 specification
Device supports USB 2.0 specification
Device address: 0x0011
Current configuration value: 0x00
Number of open pipes: 0

Device Descriptor:
------------------------------
0x12	bLength
0x01	bDescriptorType
0x0200	bcdUSB
0xEF	bDeviceClass   (Miscellaneous device)
0x02	bDeviceSubClass   
0x01	bDeviceProtocol   
0x40	bMaxPacketSize0   (64 bytes)
0x1532	idVendor
0x0B00	idProduct
0x0100	bcdDevice
0x01	iManufacturer   ""
0x02	iProduct   ""
----

But what's especially strange is the PluggableUSB shortname is successfully set using the same function.

**Comment by adammunich** [comment]
I fixed the problem;

It seems like in USBCore.cpp, the setup.wlength struct element was not representing the real length of the Product Name and Manufacturing Name descriptor strings. Using sizeof() instead of the struct elements was the problem. 

else if (USB_STRING_DESCRIPTOR_TYPE == t)
	{
		if (setup.wValueL == 0) {
			desc_addr = (const uint8_t*)&STRING_LANGUAGE;
		}
		else if (setup.wValueL == IPRODUCT /* 2 */) {
			return sendStringDescriptor(STRING_PRODUCT, 2*sizeof(STRING_PRODUCT));
		}
		else if (setup.wValueL == IMANUFACTURER /* 1 */) {
			return sendStringDescriptor(STRING_MANUFACTURER, 2*sizeof(STRING_MANUFACTURER));
		}
		else if (setup.wValueL == ISERIAL /* 3 */) {
			#ifdef PLUGGABLE_USB_ENABLED
			char name[ISERIAL_MAX_LEN];
			PluggableUSB().getShortName(name);
		
			return sendStringDescriptor((uint8_t*)name, setup.wLength);
			#endif
		}
		else {
			return false;
		}
		if (*desc_addr > setup.wLength) {
			desc_length = setup.wLength;
		}
	}

I will fork the core and make a pull request

**Comment by adammunich** [comment]
Pull request is here:

https://github.com/arduino/ArduinoCore-samd/pull/275

**Comment by awatterott** [comment]
The 2nd parameter of `sendStringDescriptor()` is the maximum length and it is `2+sizeof("string")`, because of the 2byte prefix and the string is stored as ACSII (1byte), but send as UTF-16 (2bytes).

**Comment by adammunich** [comment]
I accidentally wrote "was the problem", i mean't, "fixed the problem" :-)

The original code uses setup.wlength instead of 2*sizeof("string"), which is incorrect as setup.wlength doesn't always have the right number.

**Comment by cmaglie** [comment]
The `setup.wLength` field is the maximum length of the response that should be sent by the micro (even if the descriptor is longer it should be cut at `setup.wLength`, it's the host that controls this field here).
The code IMHO is correct as it is now.
