### ISSUE TITLE
Arduino IDE Board Manager CRC check error for package download

### ISSUE THREAD

**Issue by ryanfeist1** [arduino/ArduinoCore-samd#297]
Moderators, please ensure the CRC values are correct on the server side of things.  I'm having this problem on two separate PCs when trying to install the SAMD package via board manager.

**Comment by cmaglie** [comment]
I've just tried to re-download and re-install from scratch without CRC errors.
It may be that an anti-virus or a proxy is getting in the way?
Are you using the latest version of the IDE? Could you make a screenshot of the error?

**Comment by ryanfeist1** [comment]
Downloading over our company's internal network was the problem.  Switched over to the wide open web and it worked.  Thanks for the quick response.
