### ISSUE TITLE
ZERO variant.cpp pins 8 and 9 wrong

### ISSUE THREAD

**Issue by manitou48** [arduino/ArduinoCore-samd#30]
EXTERNAL_INT_x  for pins 8 and 9 in variant.cpp for ZERO are wrong.  see 
  http://forum.arduino.cc/index.php?topic=343779

as noted in the forum thread above, pin 2 attachInterrupt() isn't working ...not sure of fix... yet

**Comment by cmaglie** [comment]
@manitou48 thanks for the report.

I confirm that there is a bug in the variant file for pins 8 and 9, the External Interrupt number was wrong.
I've a fix also for the pin 2, I'm going to submit a pull request in a moment.
