### ISSUE TITLE
Unsigned driver warning on Windows 7

### ISSUE THREAD

**Issue by PaulStoffregen** [arduino/ArduinoCore-samd#305]
When installing version SAMD version 1.6.17 into Arduino 1.8.5 on a fresh Windows 7 system, two of the driver installs give the red "Windows Security" warning.

![capture](https://user-images.githubusercontent.com/965463/36308013-ad1b6fde-12d3-11e8-8221-f6d3f2b85e7a.png)

**Comment by facchinm** [comment]
Mmmmh, that's bad... Even if the certificate **may** be expired, we surely signed the drivers before the expiration date... @cmaglie any hint?

**Comment by cmaglie** [comment]
oh no again... this is a nightmare... will check this out in the next days...

**Comment by PaulStoffregen** [comment]
Maybe it's the SHA1 issue?

**Comment by awatterott** [comment]
I use also Win7 and I get only an error for the Adafruit CPX driver. The Arduino and Genuino SAMD drivers install correctly.

**Comment by dlabun** [comment]
On my computer it's always the Adafruit drivers that throw the security errors. I've told Adafruit numerous times that their drivers aren't signed properly.

**Comment by cmaglie** [comment]
The lastest 1.6.19 should have this problem fixed.

Please comment further if this is not the case...
