### ISSUE TITLE
USB HID receive data from PC

### ISSUE THREAD

**Issue by bigdolphin** [arduino/ArduinoCore-samd#307]
Hello,
I am trying to receive the data sent from PC via USB HID library. The function USBDevice.available always return 0. Could any one help me a solution?
Thank you.
Best regards.

**Comment by facchinm** [comment]
Hi @bigdolphin, the HID library is not intended to be used directly, but as a support framework for other libraries (like [Mouse](https://github.com/arduino-libraries/mouse), [Keyboard](https://github.com/arduino-libraries/keyboard) and [MIDI](https://github.com/arduino-libraries/midiusb)). You'll need at least some glue code to implement the descriptors setup so the endpoints gets configured before `available()` can be called.
