### ISSUE TITLE
Multiple serial

### ISSUE THREAD

**Issue by PaoloP74** [arduino/ArduinoCore-samd#31]
Interesting discussion about multiple serial on Arduino zero.
http://forum.arduino.cc/index.php?topic=330559.0

**Comment by ladyada** [comment]
you can follow this tutorial to make multiple serial ports (without having to modify the board package) its pretty easy!
https://learn.adafruit.com/using-atsamd21-sercom-to-add-more-spi-i2c-serial-ports

**Comment by sandeepmistry** [comment]
I'm closing this for now, multiple serial ports are interesting, however there are no plans to support this feature in this core for now.

The Adafruit tutorial @ladyada linked to is a great resource for those wanting to modify the core to create more Sercom based port instances.
