### ISSUE TITLE
Investigate "analog read serial" sketch bricking MKR GSM 1400

### ISSUE THREAD

**Issue by sandeepmistry** [arduino/ArduinoCore-samd#333]
Reported on the forum by @BallscrewBob: https://forum.arduino.cc/index.php?topic=558995.msg3812680#msg3812680

cc/ @Rocketct

**Comment by Rocketct** [comment]
@BallscrewBob: also i have tried: File -> Examples -> 01.Basics -> AnalogReadSerial and no issue happend,  could also share you library version?

**Comment by sandeepmistry** [comment]
I'm closing this for now, we can re-open it once we have more details.
