### ISSUE TITLE
analog write frequency too high

### ISSUE THREAD

**Issue by Makeblock-official** [arduino/ArduinoCore-samd#34]
the analogWrite output pwm frequency(48M/256 = 187.5k) is too high for most h-bridge based motor drive, for example TB6612, which may cause the chip over heat. A reasonable driving frequency is around 20k for most motors.

**Comment by sandeepmistry** [comment]
Now that #151 is merged the PWM frequency is now 732.4Hz.

**Comment by ronb127** [comment]
Seems like high PWM frequency (187.5kHz) was restored in commit 74a12d0, in what seems to be a bad merge.
Was this intentional?
