### ISSUE TITLE
bootloader makefile issue .elf filename missing

### ISSUE THREAD

**Issue by better-adapted** [arduino/ArduinoCore-samd#347]
related file - ArduinoCore-samd\bootloaders\zero\makefile
platform : windows 10 / Atmel studio / arduino zero

issue : when debugging the elf output file was just getting called ".elf" and debugging would not begin

so I had to add the new line below "BOARD_ID?=arduino_zero" @ line 60
NAME?=samd21_sam_ba

[Makefile.txt](https://github.com/arduino/ArduinoCore-samd/files/2294225/Makefile.txt)

**Comment by facchinm** [comment]
@better-adapted we never noticed it because we normally run https://github.com/arduino/ArduinoCore-samd/blob/master/bootloaders/zero/build_all_bootloaders.sh#L5 , whould you mind opening a PR with that extra line? Thanks!

**Comment by facchinm** [comment]
Solved by merging #351, thanks!
