### ISSUE TITLE
tone() will stop even without duration set

### ISSUE THREAD

**Issue by gitMichael** [arduino/ArduinoCore-samd#360]
For instance `tone(pin, 35000);` will stop after about 17.4 hours.

Reason: [Line 117 tone.cpp](https://github.com/arduino/ArduinoCore-samd/blob/cd52f7148f38d94395ba48aa6346247e8ba7a643/cores/arduino/Tone.cpp#L117)
toggleCount should be set to -1 to loop forever but will be to 2^32 because missing suffix `-1LL` or `INT64_C(-1)` for an int64 constant.

**Comment by sandeepmistry** [comment]
Hi @gitMichael,

Would you like to open a pull request for this suggestion?

**Comment by gitMichael** [comment]
No, I wouldn't. I don't like to fork / fix / pull and at long last to garbage github because of a simple two-char coding failure that will be committed maybe in months. I'm sorry.
