### ISSUE TITLE
Missing sam.h

### ISSUE THREAD

**Issue by paulcyr** [arduino/ArduinoCore-samd#363]
Version: 1.6.19

There is an `#include "sam.h"` on line 48 of `cores/arduino/Arduino.h`.

However, sam.h is missing.

**Comment by facchinm** [comment]
HI @paulcyr ,
"sam.h" include comes from https://github.com/arduino/ArduinoModule-CMSIS-ATMEL , which is a dependency of the samd core if it gets downloaded via Board Manager.
