### ISSUE TITLE
SPI_MIN_CLOCK_DIVIDER adjustment

### ISSUE THREAD

**Issue by manitou48** [arduino/ArduinoCore-samd#387]

**Comment by manitou48** [comment]
I tested running SPI @24mhz on M4 express, and signals looked good on scope. I would suggest changing the MIN_CLOCK_DIVIDER to 24 mhz rather than the conservative 12 mhz
**#define SPI_MIN_CLOCK_DIVIDER (uint8_t)(1 + ((F_CPU - 1) / 24000000))**
and let the user have the option of selecting 24  MHz in the SPISetting()

**Comment by sandeepmistry** [comment]
This core only supports the SAMD21, so this issue is not applicable.
