### ISSUE TITLE
SERIAL_BUFFER_SIZE

### ISSUE THREAD

**Issue by lunng** [arduino/ArduinoCore-samd#390]
To allow changing size of serial buffer, consider adding #ifdef SERIAL_BUFFER_SIZE wrapper to the RingBuffer.h

**Comment by sandeepmistry** [comment]
There is already an `#ifndef SERIAL_BUFFER_SIZE ` present in master: https://github.com/arduino/ArduinoCore-samd/blob/master/cores/arduino/RingBuffer.h#L30-L32
