### ISSUE TITLE
ATSAMD21E18A support

### ISSUE THREAD

**Issue by furieuxjk** [arduino/ArduinoCore-samd#394]
Hello!

Is ATSAMD21E18A chip supported with this core?

If yes- what should I choose as a Board if I want to program standalone SAMD21E18A chip?

**Comment by sabas1080** [comment]
SAMD21E18A is support, example of board https://github.com/ElectronicCats/Arduino_Boards_Index/tree/gh-pages/electroniccats/samd/variants/bast_pro_mini_m0

**Comment by furieuxjk** [comment]
Ok, thanks, I will try this out.

**Comment by alexwhittemore** [comment]
To elaborate a little - a few Adafruit boards (Trinket M0, maybe others?) use the E18, and the G18 is extremely similar. Their core fork with their M0 variants is at https://github.com/adafruit/ArduinoCore-samd.

**Comment by ldab** [comment]
Bear in mind that Trinket M0 is Crystalless

**Comment by sandeepmistry** [comment]
Closing this as answered.
