### ISSUE TITLE
analogRead on others pin

### ISSUE THREAD

**Issue by agdl** [arduino/ArduinoCore-samd#401]
Because of this line https://github.com/arduino/ArduinoCore-samd/blob/master/cores/arduino/wiring_analog.c#L133 is not possible to use the ADC channels on pins 2, 3, 11 and on all the MKR boards. Is it really necessary?

**Comment by sandeepmistry** [comment]
I think we should leave it as is, `analogRead(A0)` should be the same as `analogRead(0)`.

The variant should be changed to have analog pin numbers to be higher than the digital ones as per the convention in all the cores.

**Comment by sandeepmistry** [comment]
Closing this for now due to lack of feedback.

**Comment by tedtoal** [comment]
"The variant should be changed to have analog pin numbers to be higher than the digital ones as per the convention in all the cores."

But the SAMD processors have pins that can be configured as either analog OR digital.
