### ISSUE TITLE
DEFINE translation not working

### ISSUE THREAD

**Issue by milesfrankland** [arduino/ArduinoCore-samd#415]
I have been using in core 1.6.10 a line like this:
#define DEBUG_PRINTLN(x)  SerialUSB.println (x)

In my code I would enter lines like this:
DEBUG_PRINTLN("Hi Test");

Since I upgraded to 1.6.21 this is no longer working.

If I use:
SerialUSB.println("Hi Test");
on its own, it works.

**Comment by sandeepmistry** [comment]
Hi @milesfrankland,

Could you please provide a full sketch to reproduce this issue?

**Comment by milesfrankland** [comment]
I cant seem to be able to reproduce it now.
I may have had the includes below the defines that may have stopped it working?
All is good now though.
