### ISSUE TITLE
Arduino Nano 33 IoT not listed in Boards menu after update

### ISSUE THREAD

**Issue by jamesbebbington** [arduino/ArduinoCore-samd#424]
Not sure if this is an issue with the Arduino IDE (v1.8.9) or just user error, but having updated the SAMD boards to v1.8.1, I'm still not seeing the Arduino Nano 33 IoT listed in the Boards menu:

<img width="912" alt="Screenshot 2019-06-27 at 00 02 54" src="https://user-images.githubusercontent.com/5934/60220839-55d00a00-986f-11e9-8c58-2d4aaba70dda.png">

<img width="471" alt="Screenshot 2019-06-27 at 00 03 58" src="https://user-images.githubusercontent.com/5934/60220847-5a94be00-986f-11e9-9388-d8e32fa71564.png">

I've restarted the IDE, but no change.

**Comment by facchinm** [comment]
Hi @jamesbebbington, it may be a known bug of the IDE (@per1234 could probably find the right reference).
If you searched for "nano33iot" in the searchbar and already had SAMD core installed there is not the expected "Update" button but "Install".
This ends up installing 2 versions of the same core and the IDE gets confused.
Manual update procedure:
- navigate to `~/Library/Arduino15/packages/arduino/hardware/samd/`  and manually remove the older core folder
Graphical procedure:
- uninstall SAMD core 1.8.1, you should get the other core as installed, update it without searching anything in the searchbar.

Hope it helps!

**Comment by jamesbebbington** [comment]
Many thanks @facchinm, that seems to have been exactly the problem! All fixed now.
