### ISSUE TITLE
Samd 1.8.1 incorrectly renders paths in Window

### ISSUE THREAD

**Issue by andyrobinson** [arduino/ArduinoCore-samd#426]
Using Arduino IDE 1.8.9 and SAMD board driver 1.8.1, Windows 8.1 or Windows 10, I cannot upload sketches and see the following error:

Error: couldn't open C:UsersndyrAppDataLocalTemprduino_build_919417/Blink.ino.bin

The path separators and the first character of the folder name are missing.

When I use an older version of the SAMD board driver (1.6.21) everything works as expected.

**Comment by facchinm** [comment]
Hi @andyrobinson , are you targeting a Zero (Programming port) or any other board that uses openocd to upload? The report looks similar to   https://github.com/arduino/ArduinoCore-samd/issues/422 . I'm on it :wink:
