### ISSUE TITLE
Bootloader as Atmel Studio Project

### ISSUE THREAD

**Issue by AloyseTech** [arduino/ArduinoCore-samd#44]
Please add the bootloader as an Atmel Studio Project format, and/or improve the documentation on how use/build/modify/upload the bootloader.

**Comment by aethaniel** [comment]
@AloyseTech, this request has been fulfilled by https://github.com/arduino/ArduinoCore-samd/pull/47

You can close your ticket ;-)

**Comment by AloyseTech** [comment]
Yes, thank you @aethaniel :smiley:
