### ISSUE TITLE
SerialUSB receive data error

### ISSUE THREAD

**Issue by Makeblock-official** [arduino/ArduinoCore-samd#50]
arduino Zero using SerialUSB communicate with computer,the received data once more data than before, to be wrong.

**Comment by sandeepmistry** [comment]
@Makeblock-official could you please share an example sketch that can be used to reproduce the issue, along with steps to reproduce?

**Comment by Makeblock-official** [comment]
1.6.2 firmware has fixed this BUG

**Comment by cmaglie** [comment]
thanks for the feedback!
