### ISSUE TITLE
tone function random crashes

### ISSUE THREAD

**Issue by PaulStoffregen** [arduino/ArduinoCore-samd#52]
This sketch will crash after several minutes running on Arduino Zero.  Serial output stops, and the frequency on pin 5 becomes approx 258 kHz.

    void setup() {
      Serial.begin(115200);
      while (!Serial && millis() < 1500) ;
      delay(10);
      Serial.println("Tone Issue Test");
      delay(20);
    }

    void loop() {
      int frequency = 1500 + random(800);
      tone(5, frequency);
      Serial.println(frequency);
      delayMicroseconds(random(10000));
    }

**Comment by aethaniel** [comment]
Hi @PaulStoffregen, not yet as I didn't implement this API. I will check the code with @agdl but not before next Wednesday, unfortunately.

**Comment by PaulStoffregen** [comment]
I'm in no hurry.  Just wanted to make sure you knew about the crashing.

**Comment by agdl** [comment]
@PaulStoffregen try this please https://github.com/arduino/ArduinoCore-samd/tree/toneFix

Your sketch has been running for 2 hours
