### ISSUE TITLE
Why is the MKR1010 VIN 5V and not 12V

### ISSUE THREAD

**Issue by rjs5327** [arduino/ArduinoCore-samd#528]
I been looking over the wiring diagrams and i see that the 5V goes to BQ24195L  Which is the battery charger Chip.  So that chip can handle 3.9V -17V  upline to the Vin all i see is R19 to ground and a moffset transistor that looks to be switching between Vin and 5V i think that is to not back feed the 5V which is powered by the USB or if someone hooks 5V to the 5V pin on the board which will power it fine. 

So if im right then the Vin can take 12VDC since the moffset chip is rated to 30V and the charger is rated to 17V only issue i see is the LED is at 390Ohm which is 5V resistance for the LED.  So all it would take to update this board to allow a wider input voltage would be to update the resistors.  And maybe put a diode in to prevent back feeding through the moffset if there is leakage to the 5V line.  

Has anyone tried putting 12V to VIN ?  Since it looks like the SW output PWM to get a system Voltage of 3-3.7V depending on the set-point set in the register.   So only other issue i can see is the Capacitors may be a little light.  

Anyone have any experience here?

**Comment by pnndra** [comment]
you're right in saying that VIN can be higher. LED series resistor is actually a bit too low for that as you noticed as it would pump something more than 30mA. input capacitor (C14) is 25V so it will be absolutely fine

**Comment by ksmith3036** [comment]
Would an input of 9 V be fine, that should be just over 20 mA on the LED?

**Comment by alranel** [comment]
Closing this issue as not related to the SAMD core development. Please use the forum for hardware-related discussions. Thank you!
