### ISSUE TITLE
[Feature Request] Add LZSS compression for 2nd stage bootloaders

### ISSUE THREAD

**Issue by aentinger** [arduino/ArduinoCore-samd#539]
The algorithm can be found [here](https://oku.edu.mie-u.ac.jp/~okumura/compression/lzss.c).

**Comment by WestfW** [comment]
Why?

**Comment by aentinger** [comment]
Because of internal requirements to use the SFUs with OTA in connection with Arduino IoT Cloud. Closing this because it has already been done.
