### ISSUE TITLE
Next release date?

### ISSUE THREAD

**Issue by pixelpixi** [arduino/ArduinoCore-samd#54]
Hello. I was wondering if there is an expected date for the next release of the SamD core? The last one was in July, so it's been quite a while. I'm getting ready to ship my product and it would help a lot to have a new release that includes the fixes which have gone in since July.

Any info you can provide on the release schedule would help a lot. Thanks!

**Comment by cmaglie** [comment]
SAMD Core 1.6.2 and Arduino IDE 1.6.6 have been released

**Comment by pixelpixi** [comment]
Thanks, and congrats on getting the latest version out!
