### ISSUE TITLE
Error while writing flash memory - Arduino Nano 33 IoT

### ISSUE THREAD

**Issue by tessi** [arduino/ArduinoCore-samd#580]
Hi :)

I just received an original Arduino nano 33 IoT and wanted to test the wifi. The firmware check told me I need to update, and I followed the instructions to update the firmware. Instead of the nice success-message, I received the following

<img width="933" alt="Screenshot 2020-12-16 at 12 56 45" src="https://user-images.githubusercontent.com/206108/102354971-864bbc80-3fab-11eb-9219-5ab1c974dcf6.png">

Used versions:

* Arduino GUI: 1.8.13
* WiFiNINA: 1.8.0
* WiFi101-FirmwareUpdater-Plugin: the bundled version and [version 0.10.12](https://github.com/arduino/WiFi101-FirmwareUpdater-Plugin/releases/tag/v0.10.12)
* macOS catalina (10.15.7)

The flashing failed multiple times even after restarting, reconnecting, re-flashing things multiple times.
The firmware-check now reports that it can't connect to the wifi module (it used to work before):

```
14:36:58.459 -> WiFiNINA firmware check.
14:36:58.459 -> 
14:36:59.172 -> Communication with WiFi module failed!
```

I am at a loss on how to continue debugging this. Do you have any hints?
How could I resolve this issue and is it even something I should report here?

Note: I would be happy to ignore this issue, but now I can't use wifi from normal sketches anymore, which is a little frustrating.

**Comment by Damiasroca** [comment]
> Hi @tessi and @Damiasroca ,
> it looks like the issue has been caused by samd core 1.8.10 release. I'm moving the issue on that repo to ease keeping track of it. In the meantime, please revert to samd core 1.8.9 if you need to update the firmware. Will keep you posted as soon as the issue is solved 🙂

Downgrading indeed did the trick, Up and running again. Thank you

**Comment by tessi** [comment]
<img width="373" alt="Screenshot 2020-12-17 at 20 41 52" src="https://user-images.githubusercontent.com/206108/102535571-af05ac00-40a8-11eb-95ec-e957229e8b18.png">

Downgrading indeed worked, thank you for the super helpful and quick response @facchinm  and the fix in progress @aentinger  ❤️
