### ISSUE TITLE
USB/PluggableUSB.h not found on 1.8.10

### ISSUE THREAD

**Issue by ElectroTechnique** [arduino/ArduinoCore-samd#585]
Using USB-MIDI library to use native port on M0 Pro. Compiles on 1.8.9 and earlier. Fails on 1.8.10 with no such library for USB/PluggableUSB.h

**Comment by facchinm** [comment]
Hi @ElectroTechnique ,
thanks for reporting! I patched the library here https://github.com/arduino-libraries/MIDIUSB/commit/80b6fac501702a268d7f9ab9702333c5d059e059 , the new version (1.0.5) should be available in a few hours.
