### ISSUE TITLE
Recent change to this core breaks arduino recommended SerialFlash Library

### ISSUE THREAD

**Issue by sambartle** [arduino/ArduinoCore-samd#633]
The following commit causes problems with the SerialFlash library recommended by Arduino for MKR MEM Shield: https://github.com/arduino/ArduinoCore-samd/commit/738a0e9d1e7998c3b0c546ad432ac6b2047fa1ec

I assume either changes may need to be made to the library to accommodate this fix to the core, or a tweak to the change here to accomodate the library.. but it is beyond my current level of understanding how to resolve unfortunately.

See: https://github.com/PaulStoffregen/SerialFlash/issues/79 for full details.

**Comment by facchinm** [comment]
Hi @sambartle ,
the issue should be fixed by https://github.com/arduino/ArduinoCore-samd/pull/622 , if you could test it and report back it would speedup the merge.
