### ISSUE TITLE
burning the SAM-BA bootloader with an external programmer (e.g. Atmel-ICE) [Zero]

### ISSUE THREAD

**Issue by Dirk67** [arduino/ArduinoCore-samd#7]
burning the SAM-BA bootloader out of the IDE works fine when using the EDBG-chip
(choosing "Arduino Zero (Programming Port)" as the board)

but it does not work when using a external programmer like Atmel-ICE (choosing "Arduino Zero (Native USB Port)" as the board)

by adding this two lines to the file:
C:\Users\USERNAME\AppData\Roaming\Arduino15\packages\arduino\hardware\samd\1.6.0\boards.txt
(at the end of the part for the "Arduino Zero (Native USB Port)")
the problem is gone
(see --> http://forum.arduino.cc/index.php?topic=330699.0 )
__________________________________
arduino_zero_native.bootloader.tool=openocd
arduino_zero_native.bootloader.file=zero/samd21_sam_ba.bin

**Comment by cmaglie** [comment]
Thank you!
