### ISSUE TITLE
Warning in USBCore.cpp:649:8

### ISSUE THREAD

**Issue by unbiot** [arduino/ArduinoCore-samd#70]
I'm getting the following warning when trying to compile any of the examples with the SmartEverything board:

In member function 'uint32_t USBDeviceClass::send(uint32_t, const void*, uint32_t)':
\arduino\hardware\samd\1.6.2\cores\arduino\USB\USBCore.cpp:649:8: warning: pointer of type 'void *' used in arithmetic [-Wpointer-arith]
data += length;
     ^

**Comment by sandeepmistry** [comment]
Resolved by #85.
