### ISSUE TITLE
digitalRead() broken on pins in output mode.

### ISSUE THREAD

**Issue by WestfW** [arduino/ArduinoCore-samd#79]
Apparently "pinMode(pin, OUTPUT)" will clear the INEN bit for the GPIO pin in question, preventing digitalRead() (or direct port access) from being able to read the current output state of an output pin, and breaking trivial statements like:
    digitalWrite(13, ! digitalRead(13));  // toggle LED
As far as I can tell, there should never be a reason to disable input on the GPIO pins (PORT_PINCFG_INEN bit cleared in pincfg), except *maybe* when the pin is used for analog input.

http://forum.arduino.cc/index.php?topic=367517

**Comment by WestfW** [comment]
(also be careful not to clear INEN when setting PULLEN)

**Comment by sandeepmistry** [comment]
@WestfW agreed, I've submitted #101 to resolve this, please review or test it out if you have time.

**Comment by sandeepmistry** [comment]
Closing since #101 is merged now.
