### ISSUE TITLE
Wire.begin(address) address irelevant

### ISSUE THREAD

**Issue by arkoulikosta** [arduino/ArduinoCore-samd#93]
With the hourly build 47 the zero works as a i2c slave 
but responds to any address regardless the declaration in the begin function.

**Comment by sandeepmistry** [comment]
@arkoulikosta I've submitted #95 to resolve this, could you please try it out?

**Comment by arkoulikosta** [comment]
@sandeepmistry Tried it and it works great! thanks!!! please include this change in the next release!

**Comment by sandeepmistry** [comment]
@arkoulikosta great, thanks for trying!
